Vagrant.configure("2") do |config|
    config.vm.define "server" do |server|
        server.vm.box = "ubuntu/jammy64"
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "192.168.56.10"
    end

    config.vm.define "client" do |client|
        client.vm.box = "ubuntu/jammy64"
        client.vm.hostname = "client"
        client.vm.network "private_network", ip: "192.168.56.11"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "inventory"
    end
end
    