apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress-node2
  labels:
    type: local
spec:
  storageClassName: local-storage       # Класс хранилища
  capacity:
    storage: 1Gi                       # Размер хранилища
  accessModes:
    - ReadWriteOnce                    # Режим доступа
  local:
    path: /vagrant/wordpress-data  # Путь на второй ноде
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-node2    # имя второй ноды
